version: '3'
services:
  library:
    build: .
    volumes:
      - "./:/usr/src/app"
  challenge:
    build: ./codechallenge
    volumes:
      - "./codechallenge:/usr/src/app"
    ports:
      - 8080:8080
